/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Photo = {
  _id: string;
  _type: 'photo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    credit?: string;
    _type: 'image';
  };
  altText?: string;
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'category';
  };
  tags?: Array<string>;
};

export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  publishedAt?: string;
  highlight?: boolean;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Photo
  | Post
  | Category
  | BlockContent
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: highlightedPostsQuery
// Query: *[_type == "post" && highlight == true] | order(publishedAt desc) {  _id,  title,  slug,  mainImage {    asset-> {      _id,      url    },    alt  },  publishedAt,  categories[]-> {    _id,    title  }}
export type HighlightedPostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  publishedAt: string | null;
  categories: null;
}>;
// Variable: allPostsQuery
// Query: *[_type == "post"] | order(publishedAt desc) {  _id,  title,  slug,  mainImage {    asset-> {      _id,      url    },    alt  },  publishedAt,  categories[]-> {    _id,    title  },  body}
export type AllPostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  publishedAt: string | null;
  categories: null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  > | null;
}>;
// Variable: paginatedPostsQuery
// Query: *[_type == "post"] | order(publishedAt desc) [$start...$end] {  _id,  title,  slug,  mainImage {    asset-> {      _id,      url    },    alt  },  publishedAt,  categories[]-> {    _id,    title  },  body}
export type PaginatedPostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  publishedAt: string | null;
  categories: null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  > | null;
}>;
// Variable: postsCountQuery
// Query: count(*[_type == "post"])
export type PostsCountQueryResult = number;
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug][0]{  _id,  title,  slug,  body,  mainImage {    asset-> {      _id,      url    },    alt  },  publishedAt,  categories[]-> {    _id,    title  }}
export type PostQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  > | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  publishedAt: string | null;
  categories: null;
} | null;
// Variable: categoriesQuery
// Query: *[_type == "category"] | order(title asc) {  _id,  title,  slug}
export type CategoriesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
}>;
// Variable: photosByCategoryQuery
// Query: *[_type == "photo" && category->slug.current == $slug] | order(_createdAt desc) {  _id,  title,  image {    asset-> {      _id,      url    },    caption,    credit  },  altText,  category-> {    _id,    title,    slug  },  tags}
export type PhotosByCategoryQueryResult = Array<{
  _id: string;
  title: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    caption: string | null;
    credit: string | null;
  } | null;
  altText: string | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  tags: Array<string> | null;
}>;
// Variable: photoCategoriesQuery
// Query: *[_type == "category"] | order(title asc) {  _id,  title,  slug,  description,  "photoCount": count(*[_type == "photo" && category->_id == ^._id])}
export type PhotoCategoriesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  photoCount: number;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "post" && highlight == true] | order(publishedAt desc) {\n  _id,\n  title,\n  slug,\n  mainImage {\n    asset-> {\n      _id,\n      url\n    },\n    alt\n  },\n  publishedAt,\n  categories[]-> {\n    _id,\n    title\n  }\n}': HighlightedPostsQueryResult;
    '*[_type == "post"] | order(publishedAt desc) {\n  _id,\n  title,\n  slug,\n  mainImage {\n    asset-> {\n      _id,\n      url\n    },\n    alt\n  },\n  publishedAt,\n  categories[]-> {\n    _id,\n    title\n  },\n  body\n}': AllPostsQueryResult;
    '*[_type == "post"] | order(publishedAt desc) [$start...$end] {\n  _id,\n  title,\n  slug,\n  mainImage {\n    asset-> {\n      _id,\n      url\n    },\n    alt\n  },\n  publishedAt,\n  categories[]-> {\n    _id,\n    title\n  },\n  body\n}': PaginatedPostsQueryResult;
    'count(*[_type == "post"])': PostsCountQueryResult;
    '*[_type == "post" && slug.current == $slug][0]{\n  _id,\n  title,\n  slug,\n  body,\n  mainImage {\n    asset-> {\n      _id,\n      url\n    },\n    alt\n  },\n  publishedAt,\n  categories[]-> {\n    _id,\n    title\n  }\n}': PostQueryResult;
    '*[_type == "category"] | order(title asc) {\n  _id,\n  title,\n  slug\n}': CategoriesQueryResult;
    '*[_type == "photo" && category->slug.current == $slug] | order(_createdAt desc) {\n  _id,\n  title,\n  image {\n    asset-> {\n      _id,\n      url\n    },\n    caption,\n    credit\n  },\n  altText,\n  category-> {\n    _id,\n    title,\n    slug\n  },\n  tags\n}': PhotosByCategoryQueryResult;
    '*[_type == "category"] | order(title asc) {\n  _id,\n  title,\n  slug,\n  description,\n  "photoCount": count(*[_type == "photo" && category->_id == ^._id])\n}': PhotoCategoriesQueryResult;
  }
}
