import type { Metadata } from 'next';
import { Poppins, Courier_Prime, Cutive_Mono } from 'next/font/google';
import './globals.css';
import ScrollProgress from '@/components/ui/ScrollProgress';
import Footer from '@/components/Footer';
import { Toaster } from '@/components/ui/sonner';

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: ['400', '500', '600', '700'],
});

const courierPrime = Courier_Prime({
  subsets: ['latin'],
  variable: '--font-serif',
  weight: ['400', '700'],
});

const cutiveMono = Cutive_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      suppressContentEditableWarning={true}
      spellCheck={true}
      className='dark'
    >
      <body
        className={`${poppins.variable} ${courierPrime.variable} ${cutiveMono.variable} antialiased`}
      >
        <ScrollProgress />
        {children}
        <Toaster />
        <Footer/>
      </body>
    </html>
  );
}
